#!/usr/bin/env node
'use strict';

var program = require('commander');

program
.command('create <repo>', 'Create a new repository named "repo"')
.command('list', 'List the repositories created')
.command('info <repo>', 'Get the repository metadata')
.command('getacl <repo>', 'Get the acls set for the repository')
.command('setacl <repo> <user> [acl]', 'Set (or remove) an acl for "user" on "repo"')
.parse(process.argv);